### ISSUE TITLE
Self-Host + Other questions

### ISSUE THREAD

**Issue by LeDeathAmongst** [Millionxsam/DisFuse#8]
So, i'm trying to selfhost but idk how.
I am also trying to use the blocks and such on the *official* instance, and no luck on adding values.

**Comment by LeDeathAmongst** [comment]
Also, how does the API work? 
When i do the selfhost, i get most of it on vercel, but i keep getting "Invalid OAuth URL" even though it's the same as thats on dev portal-

**Comment by Millionxsam** [comment]
> So, i'm trying to selfhost but idk how.

Once you export your project, it will download all your bot files, including instructions.txt which has instructions on how to host your bot on different services (including self-host)
![image](https://github.com/user-attachments/assets/29d1636c-e64c-467b-8a93-3847ce31f4e6)
![image](https://github.com/user-attachments/assets/521c31bc-d9aa-498c-9684-8bf076c63cd0)


> I am also trying to use the blocks and such on the _official_ instance, and no luck on adding values.

I'm not sure what you mean by this.

> When i do the selfhost, i get most of it on vercel, but i keep getting "Invalid OAuth URL" even though it's the same as thats on dev portal-

Join our discord server and create a post in #support, because it's easier for us to communicate see what's wrong
https://discord.gg/disfuse
